import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import { ReactReduxProvider, ThemeProvider } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Home page",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ThemeProvider>
			<html lang="en">
				<body className={inter.className}>
					<ReactReduxProvider>{children}</ReactReduxProvider>
				</body>
			</html>
		</ThemeProvider>
	);
}
